// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: course.sql

package query

import (
	"context"

	"github.com/lib/pq"
)

const getCourse = `-- name: GetCourse :one
SELECT
    c.code, c.title, c.prereq, c.kind, c.objectives, c.content, c.book_names, c.outcomes,
    CAST(ARRAY(SELECT bs.branch FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS branches,
    CAST(ARRAY(SELECT bs.semester FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS semesters,
    CAST(ARRAY(SELECT bs.credits FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS credits
FROM
    course AS c
WHERE
    c.code = $1
`

type GetCourseRow struct {
	Code       string   `json:"code"`
	Title      string   `json:"title"`
	Prereq     []string `json:"prereq"`
	Kind       string   `json:"kind"`
	Objectives []string `json:"objectives"`
	Content    string   `json:"content"`
	BookNames  []string `json:"book_names"`
	Outcomes   []string `json:"outcomes"`
	Branches   []string `json:"branches"`
	Semesters  []string `json:"semesters"`
	Credits    []string `json:"credits"`
}

func (q *Queries) GetCourse(ctx context.Context, code string) (GetCourseRow, error) {
	row := q.db.QueryRowContext(ctx, getCourse, code)
	var i GetCourseRow
	err := row.Scan(
		&i.Code,
		&i.Title,
		pq.Array(&i.Prereq),
		&i.Kind,
		pq.Array(&i.Objectives),
		&i.Content,
		pq.Array(&i.BookNames),
		pq.Array(&i.Outcomes),
		pq.Array(&i.Branches),
		pq.Array(&i.Semesters),
		pq.Array(&i.Credits),
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT
    c.code, c.title, c.prereq, c.kind, c.objectives, c.content, c.book_names, c.outcomes,
    CAST(ARRAY(SELECT bs.branch FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS branches,
    CAST(ARRAY(SELECT bs.semester FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS semesters,
    CAST(ARRAY(SELECT bs.credits FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS credits
FROM
    course AS c
`

type GetCoursesRow struct {
	Code       string   `json:"code"`
	Title      string   `json:"title"`
	Prereq     []string `json:"prereq"`
	Kind       string   `json:"kind"`
	Objectives []string `json:"objectives"`
	Content    string   `json:"content"`
	BookNames  []string `json:"book_names"`
	Outcomes   []string `json:"outcomes"`
	Branches   []string `json:"branches"`
	Semesters  []string `json:"semesters"`
	Credits    []string `json:"credits"`
}

func (q *Queries) GetCourses(ctx context.Context) ([]GetCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesRow
	for rows.Next() {
		var i GetCoursesRow
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			pq.Array(&i.Prereq),
			&i.Kind,
			pq.Array(&i.Objectives),
			&i.Content,
			pq.Array(&i.BookNames),
			pq.Array(&i.Outcomes),
			pq.Array(&i.Branches),
			pq.Array(&i.Semesters),
			pq.Array(&i.Credits),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesByBranch = `-- name: GetCoursesByBranch :many
SELECT
    c.code, c.title, c.prereq, c.kind, c.objectives, c.content, c.book_names, c.outcomes,
    CAST(ARRAY(SELECT bs.branch FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS branches,
    CAST(ARRAY(SELECT bs.semester FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS semesters,
    CAST(ARRAY(SELECT bs.credits FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS credits
FROM
    course AS c
WHERE
    c.code IN (SELECT DISTINCT bs.code FROM branch_specifics AS bs WHERE bs.branch = $1)
`

type GetCoursesByBranchRow struct {
	Code       string   `json:"code"`
	Title      string   `json:"title"`
	Prereq     []string `json:"prereq"`
	Kind       string   `json:"kind"`
	Objectives []string `json:"objectives"`
	Content    string   `json:"content"`
	BookNames  []string `json:"book_names"`
	Outcomes   []string `json:"outcomes"`
	Branches   []string `json:"branches"`
	Semesters  []string `json:"semesters"`
	Credits    []string `json:"credits"`
}

func (q *Queries) GetCoursesByBranch(ctx context.Context, branch string) ([]GetCoursesByBranchRow, error) {
	rows, err := q.db.QueryContext(ctx, getCoursesByBranch, branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesByBranchRow
	for rows.Next() {
		var i GetCoursesByBranchRow
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			pq.Array(&i.Prereq),
			&i.Kind,
			pq.Array(&i.Objectives),
			&i.Content,
			pq.Array(&i.BookNames),
			pq.Array(&i.Outcomes),
			pq.Array(&i.Branches),
			pq.Array(&i.Semesters),
			pq.Array(&i.Credits),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesByBranchAndSemester = `-- name: GetCoursesByBranchAndSemester :many
SELECT
    c.code, c.title, c.prereq, c.kind, c.objectives, c.content, c.book_names, c.outcomes,
    CAST(ARRAY(SELECT bs.branch FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS branches,
    CAST(ARRAY(SELECT bs.semester FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS semesters,
    CAST(ARRAY(SELECT bs.credits FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS credits
FROM
    course AS c
WHERE
    c.code IN (SELECT DISTINCT bs.code FROM branch_specifics AS bs WHERE bs.branch = $1 AND bs.semester = $2)
`

type GetCoursesByBranchAndSemesterParams struct {
	Branch   string `json:"branch"`
	Semester int16  `json:"semester"`
}

type GetCoursesByBranchAndSemesterRow struct {
	Code       string   `json:"code"`
	Title      string   `json:"title"`
	Prereq     []string `json:"prereq"`
	Kind       string   `json:"kind"`
	Objectives []string `json:"objectives"`
	Content    string   `json:"content"`
	BookNames  []string `json:"book_names"`
	Outcomes   []string `json:"outcomes"`
	Branches   []string `json:"branches"`
	Semesters  []string `json:"semesters"`
	Credits    []string `json:"credits"`
}

func (q *Queries) GetCoursesByBranchAndSemester(ctx context.Context, arg GetCoursesByBranchAndSemesterParams) ([]GetCoursesByBranchAndSemesterRow, error) {
	rows, err := q.db.QueryContext(ctx, getCoursesByBranchAndSemester, arg.Branch, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesByBranchAndSemesterRow
	for rows.Next() {
		var i GetCoursesByBranchAndSemesterRow
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			pq.Array(&i.Prereq),
			&i.Kind,
			pq.Array(&i.Objectives),
			&i.Content,
			pq.Array(&i.BookNames),
			pq.Array(&i.Outcomes),
			pq.Array(&i.Branches),
			pq.Array(&i.Semesters),
			pq.Array(&i.Credits),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesBySemester = `-- name: GetCoursesBySemester :many
SELECT
    c.code, c.title, c.prereq, c.kind, c.objectives, c.content, c.book_names, c.outcomes,
    CAST(ARRAY(SELECT bs.branch FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS branches,
    CAST(ARRAY(SELECT bs.semester FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS semesters,
    CAST(ARRAY(SELECT bs.credits FROM branch_specifics AS bs WHERE bs.code = c.code) AS VARCHAR[]) AS credits
FROM
    course AS c
WHERE
    c.code IN (SELECT DISTINCT bs.code FROM branch_specifics AS bs WHERE bs.semester = $1)
`

type GetCoursesBySemesterRow struct {
	Code       string   `json:"code"`
	Title      string   `json:"title"`
	Prereq     []string `json:"prereq"`
	Kind       string   `json:"kind"`
	Objectives []string `json:"objectives"`
	Content    string   `json:"content"`
	BookNames  []string `json:"book_names"`
	Outcomes   []string `json:"outcomes"`
	Branches   []string `json:"branches"`
	Semesters  []string `json:"semesters"`
	Credits    []string `json:"credits"`
}

func (q *Queries) GetCoursesBySemester(ctx context.Context, semester int16) ([]GetCoursesBySemesterRow, error) {
	rows, err := q.db.QueryContext(ctx, getCoursesBySemester, semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesBySemesterRow
	for rows.Next() {
		var i GetCoursesBySemesterRow
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			pq.Array(&i.Prereq),
			&i.Kind,
			pq.Array(&i.Objectives),
			&i.Content,
			pq.Array(&i.BookNames),
			pq.Array(&i.Outcomes),
			pq.Array(&i.Branches),
			pq.Array(&i.Semesters),
			pq.Array(&i.Credits),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
