// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: member.sql

package query

import (
	"context"

	"github.com/lib/pq"
)

const createClubMember = `-- name: CreateClubMember :exec
INSERT INTO club_member (
    club_name, roll_number, position, extra_groups
)
VALUES (
    (SELECT c.name FROM club AS c WHERE c.name = $1 OR c.alias = $1),
    $2,
    $3,
    $4
)
`

type CreateClubMemberParams struct {
	ClubNameOrAlias string   `json:"club_name_or_alias"`
	RollNumber      string   `json:"roll_number"`
	Position        string   `json:"position"`
	ExtraGroups     []string `json:"extra_groups"`
}

func (q *Queries) CreateClubMember(ctx context.Context, arg CreateClubMemberParams) error {
	_, err := q.db.ExecContext(ctx, createClubMember,
		arg.ClubNameOrAlias,
		arg.RollNumber,
		arg.Position,
		pq.Array(arg.ExtraGroups),
	)
	return err
}

const deleteClubMember = `-- name: DeleteClubMember :exec
DELETE FROM
    club_member
WHERE
    club_member.club_name = (SELECT c.name FROM club AS c WHERE c.name = $1 OR c.alias = $1)
    AND club_member.roll_number = $2
`

type DeleteClubMemberParams struct {
	ClubNameOrAlias string `json:"club_name_or_alias"`
	RollNumber      string `json:"roll_number"`
}

func (q *Queries) DeleteClubMember(ctx context.Context, arg DeleteClubMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteClubMember, arg.ClubNameOrAlias, arg.RollNumber)
	return err
}
