// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package query

import (
	"database/sql"
)

type Hostel struct {
	Number     string
	Name       sql.NullString
	WardenName sql.NullString
}

type Student struct {
	RollNumber   int32
	Section      string
	SubSection   string
	Name         string
	Gender       sql.NullString
	Mobile       sql.NullString
	Birthday     sql.NullTime
	Email        string
	Batch        int16
	HostelNumber sql.NullString
	RoomNumber   sql.NullString
	DiscordUid   sql.NullInt64
	Verified     bool
}
