// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: query.sql

package query

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const getAllCourses = `-- name: GetAllCourses :many
SELECT code, title, branch, semester, credits, prereq, type, objectives, content, books, outcomes FROM course
`

func (q *Queries) GetAllCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, getAllCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			&i.Branch,
			&i.Semester,
			pq.Array(&i.Credits),
			pq.Array(&i.Prereq),
			&i.Type,
			&i.Objectives,
			&i.Content,
			&i.Books,
			&i.Outcomes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFaculty = `-- name: GetAllFaculty :many
SELECT group_name, name, mobile FROM group_faculty
`

func (q *Queries) GetAllFaculty(ctx context.Context) ([]GroupFaculty, error) {
	rows, err := q.db.QueryContext(ctx, getAllFaculty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupFaculty
	for rows.Next() {
		var i GroupFaculty
		if err := rows.Scan(&i.GroupName, &i.Name, &i.Mobile); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGroupAdmins = `-- name: GetAllGroupAdmins :many
SELECT group_name, position, roll_number FROM group_admin
`

func (q *Queries) GetAllGroupAdmins(ctx context.Context) ([]GroupAdmin, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroupAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupAdmin
	for rows.Next() {
		var i GroupAdmin
		if err := rows.Scan(&i.GroupName, &i.Position, &i.RollNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGroupMembers = `-- name: GetAllGroupMembers :many
SELECT roll_number, group_name FROM group_member
`

func (q *Queries) GetAllGroupMembers(ctx context.Context) ([]GroupMember, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroupMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(&i.RollNumber, &i.GroupName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGroupSocials = `-- name: GetAllGroupSocials :many
SELECT name, type, link FROM group_social
`

func (q *Queries) GetAllGroupSocials(ctx context.Context) ([]GroupSocial, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroupSocials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupSocial
	for rows.Next() {
		var i GroupSocial
		if err := rows.Scan(&i.Name, &i.Type, &i.Link); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT groups.name, alias, branch, kind, description, group_discord.name, id, invite, fresher_role, sophomore_role, junior_role, senior_role, guest_role FROM groups NATURAL JOIN group_discord
`

type GetAllGroupsRow struct {
	Name          string
	Alias         sql.NullString
	Branch        sql.NullString
	Kind          sql.NullString
	Description   sql.NullString
	Name_2        sql.NullString
	ID            sql.NullInt64
	Invite        sql.NullString
	FresherRole   sql.NullInt64
	SophomoreRole sql.NullInt64
	JuniorRole    sql.NullInt64
	SeniorRole    sql.NullInt64
	GuestRole     sql.NullInt64
}

func (q *Queries) GetAllGroups(ctx context.Context) ([]GetAllGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGroupsRow
	for rows.Next() {
		var i GetAllGroupsRow
		if err := rows.Scan(
			&i.Name,
			&i.Alias,
			&i.Branch,
			&i.Kind,
			&i.Description,
			&i.Name_2,
			&i.ID,
			&i.Invite,
			&i.FresherRole,
			&i.SophomoreRole,
			&i.JuniorRole,
			&i.SeniorRole,
			&i.GuestRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchCourses = `-- name: GetBranchCourses :many
SELECT code, title, branch, semester, credits, prereq, type, objectives, content, books, outcomes FROM course
WHERE branch = $1
`

func (q *Queries) GetBranchCourses(ctx context.Context, branch string) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, getBranchCourses, branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			&i.Branch,
			&i.Semester,
			pq.Array(&i.Credits),
			pq.Array(&i.Prereq),
			&i.Type,
			&i.Objectives,
			&i.Content,
			&i.Books,
			&i.Outcomes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourse = `-- name: GetCourse :one
SELECT code, title, branch, semester, credits, prereq, type, objectives, content, books, outcomes FROM course
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetCourse(ctx context.Context, code string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, code)
	var i Course
	err := row.Scan(
		&i.Code,
		&i.Title,
		&i.Branch,
		&i.Semester,
		pq.Array(&i.Credits),
		pq.Array(&i.Prereq),
		&i.Type,
		&i.Objectives,
		&i.Content,
		&i.Books,
		&i.Outcomes,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT code, title, branch, semester, credits, prereq, type, objectives, content, books, outcomes FROM course
WHERE branch = $1 AND semester = $2
`

type GetCoursesParams struct {
	Branch   string
	Semester int16
}

func (q *Queries) GetCourses(ctx context.Context, arg GetCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, getCourses, arg.Branch, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			&i.Branch,
			&i.Semester,
			pq.Array(&i.Credits),
			pq.Array(&i.Prereq),
			&i.Type,
			&i.Objectives,
			&i.Content,
			&i.Books,
			&i.Outcomes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSemesterCourses = `-- name: GetSemesterCourses :many
SELECT code, title, branch, semester, credits, prereq, type, objectives, content, books, outcomes FROM course
WHERE semester = $1
`

func (q *Queries) GetSemesterCourses(ctx context.Context, semester int16) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, getSemesterCourses, semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			&i.Branch,
			&i.Semester,
			pq.Array(&i.Credits),
			pq.Array(&i.Prereq),
			&i.Type,
			&i.Objectives,
			&i.Content,
			&i.Books,
			&i.Outcomes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudent = `-- name: GetStudent :one
SELECT roll_number, section, sub_section, name, gender, mobile, birthday, email, batch, hostel_number, room_number, discord_uid, verified FROM student
WHERE roll_number = $1
`

func (q *Queries) GetStudent(ctx context.Context, rollNumber int32) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudent, rollNumber)
	var i Student
	err := row.Scan(
		&i.RollNumber,
		&i.Section,
		&i.SubSection,
		&i.Name,
		&i.Gender,
		&i.Mobile,
		&i.Birthday,
		&i.Email,
		&i.Batch,
		&i.HostelNumber,
		&i.RoomNumber,
		&i.DiscordUid,
		&i.Verified,
	)
	return i, err
}
